### ISSUE TITLE
check if source and destination directories exist or not

### ISSUE THREAD

**Issue by rkgade** [gadeRaghav/backup-scripts-using-tar#5]
What if I pass two parameters, but folders on those names don't exist?
The script doesn't throw a dignified error message and just abruptly exits.

**Comment by gadeRaghav** [comment]
Issue resolved. The script checks weather the file that has to be backed up exists or not . If it doesn't exist , it gives an error saying " backup file not found".
If the backup file exists and destination file also exitst , backup is done.
If the backup file exists and destination file doesn't exist , it creates a backup file with given parameter and backup is done.
